# Web3 & Blockchain Variables
blockchain.contract.address=0xYourRealContractAddressHere
blockchain.wallet.private-key=ENTER_YOUR_PRIVATE_KEY_HERE

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/medichain
spring.datasource.username=postgres
spring.datasource.password=ENTER_DB_PASSWORD_HERE
