# Web3 & Blockchain Variables
blockchain.contract.address=Your_Contract_Address
blockchain.wallet.private-key=Your_private_key

# PostgreSQL Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/medichain
spring.datasource.username=postgres
spring.datasource.password=pass123
