# Web3 & Blockchain Variables
blockchain.contract.address=0xfd7a62abe2e55bc7a8cdd8cca5115e81fa4e4f39
blockchain.wallet.private-key=a5ec59031417f0a6f48a99b1733caf635d4e740934eb55e30dff4918d37901a8

# PostgreSQL Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/medichain
spring.datasource.username=postgres
spring.datasource.password=pass123

# H2 Database Configuration (Fallback)
# spring.datasource.url=jdbc:h2:mem:medichain
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

jwt.secret=4qQ+Xk9k/T6o2s9vG4dD8aU1cW3xZ7yR0bN5mE8lF2A=